### ISSUE TITLE
US1 : Gestion des taxes

### ISSUE THREAD

**Issue by bfouilhac** [benja330312/MegaMangaShop-FBAR#1]
En tant que vendeur, 
Je veux pouvoir Je veux pouvoir sélectionner le pays de destination de ma commande parmi une liste prédéfinie
Afin que le système applique automatiquement le bon taux de TVA dans le calcul du prix final.

**Example mapping**

Règles associées :
- Le pays doit être sélectionné parmi une liste prédéfinie.
- Chaque pays a un taux de TVA fixe associé.
- Une seule TVA par commande.

Exemple d'un achat en **France** : 
- Commande de 50€ HT
TVA de 20% 

Exemple d'un achat en **Allemagne**:
- Commande de 10€HT
TVA de 15,6%

**Comment by MontaineMarteau** [comment]
pour l'example mapping, vous devez indiquer le résultat du calcul pour bien comprendre ce qui est attendu.
