### ISSUE TITLE
US2 : Calcul des taxes (TVA)

### ISSUE THREAD

**Issue by bfouilhac** [benja330312/MegaMangaShop-FBAR#2]
En tant que vendeur,
Je veux que la TVA soit calculée automatiquement sur le montant total après remise
Afin d’obtenir le prix final TTC.

**Example mapping** 

Règles associées :

La TVA s'applique sur le montant après remise.

Exemple du calcul de la TVA pour l'**Allemagne** (15,6%) :
- Montant HT avant remise : 400€
Remise applicable : 5% (entre 300€ et 500€)
Montant après remise : 400*0.95 = 380€
TVA : 380x0.156 = 59.28€
Total TTC : 380+59.28€ = 439.85€

Cas limites
- Aucun pays sélectionné
Montant HT avant remise : 200€
Message d’erreur attendu : "Veuillez sélectionner un pays de livraison."

- Montant après remise égal à zéro
Montant HT avant remise : 150€
Remise applicable : 100% (remise exceptionnelle)
Montant après remise : 150*0 = 0€
Message d’erreur attendu : "Le montant après remise ne peut pas être nul."

**Comment by MontaineMarteau** [comment]
Vos cas limites n'apparaissent pas dans les tests.
