### ISSUE TITLE
US3 : Gestion des remises

### ISSUE THREAD

**Issue by bfouilhac** [benja330312/MegaMangaShop-FBAR#3]
En tant que vendeur,
Je veux que le système applique des remises automatiques selon le montant total HT de la commande
Afin d’inciter les clients à commander en gros volumes.

**Example mapping**

Règles associées :

Remises automatiques basées sur les seuils suivants :
- 2% pour les commandes entre 150€ et 200€.
- 3% pour les commandes entre 200€ et 300€.
- 5% pour les commandes entre 300€ et 500€.
- 7% pour les commandes entre 500€ et 1000€.
- 10% pour les commandes au-delà de 1000€.

Exemple de remise pour les différents seuils : 

- Montant HT : 180€ 
Remise applicable : 150<180<200 -> 2%
Montant HT final : 180*0.98 = 176.4€

- Montant HT : 280€ 
Remise applicable : 200<280<300 -> 3%
Montant HT final : 280*0.97 = 271.6€

- Montant HT : 380€ 
Remise applicable : 300<380<500-> 5%
Montant HT final : 380*0.95 = 361€

- Montant HT : 980€ 
Remise applicable : 500<980<1000-> 7%
Montant HT final : 980*0.93 = 911.4€

- Montant HT : 1500€ 
Remise applicable : 1000<1500 -> 10%
Montant HT final : 1500*0.9 = 1350€

**Cas limites**
- Exemple avec aucune remise (montant HT inférieur à 150€)
Montant HT : 100€
Remise applicable : Aucune (montant HT < 150€)
Montant HT final : 100€

**Cas particuliers ou erreurs :**

- Montant HT : 0€
Message d’erreur attendu : "Le montant de la commande doit être supérieur à zéro pour appliquer une remise."

- Montant HT : -50€
Message d’erreur attendu : "Le montant de la commande ne peut pas être négatif."

**Comment by MontaineMarteau** [comment]
Bravo. Vous avez utilisé la spécification de l'example mapping pour vos tests.
